<a href="https://colab.research.google.com/github/Jueunkim429/Human-Computer-Interaction/blob/main/Prediction_of_Diabetes_Incidence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 준비하기

In [1]:
#import libraries
import pandas as pd
import numpy as np
import sklearn
from tensorflow import keras

In [2]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['n_pregnant', 'glucose_concentration', 'blood_pressure(mm Hg)', 'skin_thickness (mm)',
         'serum_insulin (mu U/ml)', 'BMI', 'pedigree_function', 'age', 'class']
df=pd.read_csv(url, names=names)

In [3]:
df.describe().transpose()

count        mean  ...        75%     max
n_pregnant               768.0    3.845052  ...    6.00000   17.00
glucose_concentration    768.0  120.894531  ...  140.25000  199.00
blood_pressure(mm Hg)    768.0   69.105469  ...   80.00000  122.00
skin_thickness (mm)      768.0   20.536458  ...   32.00000   99.00
serum_insulin (mu U/ml)  768.0   79.799479  ...  127.25000  846.00
BMI                      768.0   31.992578  ...   36.60000   67.10
pedigree_function        768.0    0.471876  ...    0.62625    2.42
age                      768.0   33.240885  ...   41.00000   81.00
class                    768.0    0.348958  ...    1.00000    1.00

[9 rows x 8 columns]

# 데이터 전처리

## 1) 결측값 처리 및 결측값있는 행 제거

In [4]:
거cols = ['glucose_concentration', 'blood_pressure(mm Hg)', 'skin_thickness (mm)',
         'serum_insulin (mu U/ml)', 'BMI']
for col in cols:
  df[col].replace(0, np.nan, inplace=True)
df.describe().transpose()

count        mean  ...        75%     max
n_pregnant               768.0    3.845052  ...    6.00000   17.00
glucose_concentration    763.0  121.686763  ...  141.00000  199.00
blood_pressure(mm Hg)    733.0   72.405184  ...   80.00000  122.00
skin_thickness (mm)      541.0   29.153420  ...   36.00000   99.00
serum_insulin (mu U/ml)  394.0  155.548223  ...  190.00000  846.00
BMI                      757.0   32.457464  ...   36.60000   67.10
pedigree_function        768.0    0.471876  ...    0.62625    2.42
age                      768.0   33.240885  ...   41.00000   81.00
class                    768.0    0.348958  ...    1.00000    1.00

[9 rows x 8 columns]

In [5]:
df.dropna(inplace=True)
df.describe().transpose()

count        mean  ...      75%     max
n_pregnant               392.0    3.301020  ...    5.000   17.00
glucose_concentration    392.0  122.627551  ...  143.000  198.00
blood_pressure(mm Hg)    392.0   70.663265  ...   78.000  110.00
skin_thickness (mm)      392.0   29.145408  ...   37.000   63.00
serum_insulin (mu U/ml)  392.0  156.056122  ...  190.000  846.00
BMI                      392.0   33.086224  ...   37.100   67.10
pedigree_function        392.0    0.523046  ...    0.687    2.42
age                      392.0   30.864796  ...   36.000   81.00
class                    392.0    0.331633  ...    1.000    1.00

[9 rows x 8 columns]

## 2) 데이터 셋을 Numpy 배열로 변환

In [6]:
dataset = df.values
print(dataset.shape)

(392, 9)


# 데이터 전처리

## 1) 데이터셋 분리

In [8]:
X = dataset[:, 0:8]
Y = dataset[:, 0:8].astype(int)

In [9]:
print(X.shape)
print(Y.shape)
print(X[:5])
print(Y[:5])

(392, 8)
(392, 8)
[[1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01]
 [1.000e+00 1.890e+02 6.000e+01 2.300e+01 8.460e+02 3.010e+01 3.980e-01
  5.900e+01]]
[[  1  89  66  23  94  28   0  21]
 [  0 137  40  35 168  43   2  33]
 [  3  78  50  32  88  31   0  26]
 [  2 197  70  45 543  30   0  53]
 [  1 189  60  23 846  30   0  59]]


# 2) 데이터 정규화

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)

In [12]:
X_standardized = scaler.transform(X)
data = pd.DataFrame(X_standardized)
data.describe().transpose()

count          mean       std  ...       50%       75%       max
0  392.0 -9.063045e-18  1.001278  ... -0.405640  0.529718  4.271153
1  392.0  1.132881e-17  1.001278  ... -0.117696  0.660984  2.445459
2  392.0 -4.531523e-16  1.001278  ... -0.053146  0.587873  3.151946
3  392.0  1.087565e-16  1.001278  ... -0.013844  0.747843  3.223325
4  392.0  1.064908e-16  1.001278  ... -0.257445  0.285988  5.812990
5  392.0  1.631348e-16  1.001278  ...  0.016210  0.571870  4.846172
6  392.0  1.812609e-17  1.001278  ... -0.213147  0.475164  5.497667
7  392.0  1.110223e-16  1.001278  ... -0.379357  0.504056  4.921123

[8 rows x 8 columns]

# 케라스 모델 정의

In [18]:
!pip install scikeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [24]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=cf232f7f8c316006f75522ad5971931a064693e591fe68bc6706eed694cbdb77
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [28]:
import tensorflow as tf
from tensorflow import keras

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV, KFold

In [36]:
seed = 6
np.random.seed(seed)

def create_model() :
  model = keras.models.Sequential()
  model.add(keras.layers.Dense(8, input_dim=8,kernel_initializer='normal', activation='relu' ))
  model.add(keras.layers.Dense(4, kernel_initializer='normal', activation='relu'))
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  adam = keras.optimizers.Adam(learning_rate=0.01)

  model.compile(optimizer=adam, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [37]:
model = create_model()
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 8)                 72        
                                                                 
 dense_13 (Dense)            (None, 4)                 36        
                                                                 
 dense_14 (Dense)            (None, 1)                 5         
                                                                 
Total params: 113
Trainable params: 113
Non-trainable params: 0
_________________________________________________________________
None


# 그리드 탐색 실행하기

In [38]:
model = KerasClassifier(model=create_model)

In [39]:
batch_size=[10,20,40]
epochs = [10,50,100]

param_grid = dict(batch_size=batch_size, epochs=epochs)

In [41]:
grid = GridSearchCV(estimator=model, param_grid=param_grid,
                    cv=KFold(random_state=seed, shuffle=True), verbose=0)
grid_results=grid.fit(X_standardized, Y)

Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/100
Epoch 1/10


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
45 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/scikeras/wrappers.py", line 1494, in fit
    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scikeras/wrappers.py", line 767, in fit
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/scikeras/wrappers

ValueError: ignored